---
title: "endes-howto"
date: "`r Sys.Date()`"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE
)
```

```{r setup}
library(ENDES.PE)
```


# paquetes

```{r setup}
library(ENDES.PE)
library(srvyr)
library(tidyverse)
library(sjlabelled)
library(kableExtra)
library(scales)
```

# ENDES.PE

## Importar bases de datos

```{r, echo=FALSE}
año <- 2017

# Household
hogar <- consulta_endes(periodo = año, codigo_modulo = 64, base = "RECH0", 
                        guardar = FALSE, codificacion = "latin1") 

vivienda <- consulta_endes(periodo = año, codigo_modulo = 65, base = "RECH23",
                           guardar = FALSE, codificacion = "latin1")


# Subjects
persona <- consulta_endes(periodo = año, codigo_modulo = 64, base = "RECH1", 
                          guardar = FALSE, codificacion = "latin1")

salud <- consulta_endes(periodo = año, codigo_modulo = 414, base = "CSALUD01",
                        guardar = FALSE, codificacion = "latin1")

mujer_obs <- consulta_endes(periodo = 2017, codigo_modulo = 67, 
                            base = "RE223132", guardar = FALSE,
                            codificacion = "latin1")

mujer_lac <- consulta_endes(periodo = 2017, codigo_modulo = 70, base = "REC42",
                            guardar = FALSE, codificacion = "latin1")

mujer_ant <- consulta_endes(periodo = 2017, codigo_modulo = 74, base = "RECH5",
                            guardar = FALSE, codificacion = "latin1")
```

## Diccionarios de variables

```{r}
diccionario_encuesta(salud)
  
```

## Unión de bases

```{r}
# Unimos base de personas ("individual")
union_individuo1 <- unir_endes(base1 = persona, base2 = salud, 
                              tipo_union = "individual") %>% 
  unir_endes(base2 = mujer_ant, tipo_union = "individual")

union_individuo2 <- unir_endes(base1 = mujer_obs, base2 = mujer_lac,
                               tipo_union = "individual")

union_individuo <- unir_endes(base1 = union_individuo1, base2 = union_individuo2,
                              tipo_union = "individual")

# Unimos base de Hogar y vivienda ("hogar") 
union_vivienda <- unir_endes(base1 = hogar, base2 = vivienda, 
                             tipo_union = "hogar") 

# Union final de individuos con base de Hogares ("hogar")
base_final <- unir_endes(base1 = union_vivienda, base2 = union_individuo,
                         tipo_union = "hogar")

```


```{r}
base_final <- base_final %>% 
  filter(QSRESINF == 1)

base <- base_final %>% 
  filter(QSRESINF == 1) %>%   #filtrar por cuestionario salud
  mutate(                     #crear variables
    #hipertension
    PAMS = (QS905S+QS903S)/2, # Obtenemos la PAM sistólica de dos mediciones
    PAMD = (QS905D+QS903D)/2, # Obtenemos la PAM diastólica de dos mediciones
    HIPERTENSION  =  (PAMS>=140) | (PAMD>=90), # Definimos el criterio de HTA
    #obesidad
    PESO = ifelse(QS902 == 1 & (QS900 >= 1 & QS900 < 999), QS900,
                       ifelse(QS902 == 4, HA2/10, NA)),
    TALLA = ifelse(QS902 == 1 & (QS901 >= 1 & QS901 < 999), QS901,
                        ifelse(QS902 == 4, HA3/10, NA)),
    ha13tmp = case_when(HA13 == 0 ~ 1,
                             HA13 == 3 ~ 2,
                             HA13 == 4 ~ 3,
                             HA13 == 6 ~ 6),
    RQS902 = ifelse(QS902 == 4, ha13tmp, QS902),
    IMC = PESO/(TALLA^2)*10000,
    OBESIDAD = IMC >= 30, 
    SOBREPESO = IMC >= 25 & IMC < 30,
    SEXO = HV104,
    AREA_RESIDENCIA = HV025, 
    QUINTIL_BIENESTAR = HV270, 
    REGION_NATURAL = SHREGION,
    # Diseño de encuesta
    CONGLOMERADO=HV001,
    ESTRATO=HV022,
    PONDERACION=HV005/1000000
  ) %>% 
  filter(V213 != 1 | is.na(V213), RQS902 == 1)
```

# srvyr

## setear base según diseño muestral

```{r}
modelo <- base %>% 
  as_survey_design(id = CONGLOMERADO, strata = ESTRATO, weights = PONDERACION)

```

## Tablas de prevalencia

```{r}

hip <- modelo %>%  
  group_by(QUINTIL_BIENESTAR,SEXO) %>% 
  summarise(proportion = survey_mean(HIPERTENSION, vartype = "ci")) %>% 
  mutate(QUINTIL_BIENESTAR = as_factor(QUINTIL_BIENESTAR),
         SEXO = as_character(SEXO), enf = "Hipertensión")

hip %>%  
  mutate_at(3:5, function(x) x * 100) %>% 
  kable()
```

```{r}
obe <- modelo %>%  
  group_by(QUINTIL_BIENESTAR,SEXO) %>% 
  summarise(proportion = survey_mean(OBESIDAD, vartype = "ci")) %>% 
  mutate(QUINTIL_BIENESTAR = as_factor(QUINTIL_BIENESTAR),
         SEXO = as_character(SEXO), enf = "Obesidad") 

obe %>% 
  mutate_at(3:5, function(x) x * 100) %>%
  kable()
```

## grafico: cronicas

```{r,fig.height=4,fig.width=5,fig.align='center'}
union_all(hip,obe) %>% 
  mutate(SEXO=fct_rev(SEXO)) %>% 
  ggplot(aes(x = QUINTIL_BIENESTAR,
             y = proportion,
             colour= SEXO)) +
  geom_point(size = 2) +
  facet_grid(enf ~ SEXO) +
  geom_errorbar(width=.1, 
                aes(ymin= proportion_low, ymax= proportion_upp))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), 
                     limits = c(0,0.35)) +
  labs(title = "Enfermedades crónicas (ENDES, 2017)",
       subtitle = "Según sexo y quintil de bienestar",
       colour="Sexo",
       x = "Quintil de bienestar", 
       y = "Prevalencia")
#ggsave("figure/fig04-cronica-quintil_sexo.png",width = 5,height = 4)
```

